// 学者排行趋势数据
export const researcherTrendData = [
  { year: "2018", h_index: 28, citations: 6500, papers: 62 },
  { year: "2019", h_index: 30, citations: 7200, papers: 68 },
  { year: "2020", h_index: 32, citations: 8500, papers: 78 },
  { year: "2021", h_index: 36, citations: 11200, papers: 105 },
  { year: "2022", h_index: 38, citations: 9800, papers: 95 },
  { year: "2023", h_index: 45, citations: 12500, papers: 120 },
]

// 学者地理分布数据
export const researcherMapData = [
  { lng: 116.4074, lat: 39.9042, name: "北京大学", value: 120, researchers: 45, papers: 450, country: "中国" },
  { lng: 121.4737, lat: 31.2304, name: "复旦大学", value: 105, researchers: 36, papers: 380, country: "中国" },
  { lng: 120.0848, lat: 30.2741, name: "浙江大学", value: 95, researchers: 32, papers: 350, country: "中国" },
  { lng: 116.3328, lat: 39.9952, name: "清华大学", value: 110, researchers: 38, papers: 420, country: "中国" },
  { lng: 118.7969, lat: 32.0603, name: "南京大学", value: 85, researchers: 28, papers: 320, country: "中国" },
  { lng: 113.2644, lat: 23.1291, name: "中山大学", value: 75, researchers: 25, papers: 280, country: "中国" },
  { lng: 114.3896, lat: 30.5234, name: "武汉大学", value: 70, researchers: 22, papers: 260, country: "中国" },
  { lng: 108.9435, lat: 34.2583, name: "西安交通大学", value: 65, researchers: 20, papers: 240, country: "中国" },
  { lng: 126.6368, lat: 45.741, name: "哈尔滨工业大学", value: 60, researchers: 18, papers: 220, country: "中国" },
]

// 团队影响力趋势数据
export const teamTrendData = [
  { year: "2018", team1: 75, team2: 68, team3: 62 },
  { year: "2019", team1: 80, team2: 72, team3: 70 },
  { year: "2020", team1: 85, team2: 78, team3: 75 },
  { year: "2021", team1: 90, team2: 85, team3: 80 },
  { year: "2022", team1: 95, team2: 90, team3: 85 },
  { year: "2023", team1: 98, team2: 92, team3: 87 },
]

// 团队合作网络数据
export const teamNetworkData = {
  nodes: [
    { id: "team1", label: "基因组学与精准医学团队", cluster: "self", size: 30 },
    { id: "team2", label: "干细胞与再生医学研究团队", cluster: "partner", size: 25 },
    { id: "team3", label: "肿瘤免疫治疗研究团队", cluster: "partner", size: 25 },
    { id: "team4", label: "结构生物学与药物设计团队", cluster: "partner", size: 20 },
    { id: "team5", label: "合成生物学与基因编辑团队", cluster: "partner", size: 20 },
    { id: "team6", label: "病毒学与感染免疫研究团队", cluster: "partner", size: 18 },
    { id: "team7", label: "神经发育与疾病研究团队", cluster: "partner", size: 18 },
    { id: "team8", label: "代谢组学研究团队", cluster: "partner", size: 15 },
    { id: "team9", label: "表观遗传学研究团队", cluster: "partner", size: 15 },
    { id: "team10", label: "微生物组与健康研究团队", cluster: "partner", size: 15 },
  ],
  edges: [
    { source: "team1", target: "team2", value: 5 },
    { source: "team1", target: "team3", value: 4 },
    { source: "team1", target: "team4", value: 3 },
    { source: "team1", target: "team5", value: 4 },
    { source: "team1", target: "team6", value: 2 },
    { source: "team1", target: "team7", value: 3 },
    { source: "team1", target: "team8", value: 2 },
    { source: "team1", target: "team9", value: 3 },
    { source: "team1", target: "team10", value: 2 },
    { source: "team2", target: "team3", value: 3 },
    { source: "team2", target: "team5", value: 2 },
    { source: "team2", target: "team7", value: 2 },
    { source: "team3", target: "team4", value: 2 },
    { source: "team3", target: "team6", value: 3 },
    { source: "team4", target: "team5", value: 4 },
    { source: "team5", target: "team9", value: 2 },
    { source: "team6", target: "team10", value: 3 },
    { source: "team7", target: "team8", value: 2 },
    { source: "team8", target: "team9", value: 2 },
    { source: "team9", target: "team10", value: 1 },
  ],
}

// 机构地理分布数据
export const institutionMapData = [
  {
    lng: 116.4074,
    lat: 39.9042,
    name: "北京大学",
    value: 96,
    teams: 42,
    researchers: 380,
    papers: 4250,
    country: "中国",
  },
  {
    lng: 116.3328,
    lat: 39.9952,
    name: "清华大学",
    value: 92,
    teams: 38,
    researchers: 340,
    papers: 3800,
    country: "中国",
  },
  {
    lng: 116.2328,
    lat: 40.0952,
    name: "中国科学院",
    value: 94,
    teams: 56,
    researchers: 520,
    papers: 5100,
    country: "中国",
  },
  {
    lng: 121.4737,
    lat: 31.2304,
    name: "复旦大学",
    value: 90,
    teams: 35,
    researchers: 310,
    papers: 3500,
    country: "中国",
  },
  {
    lng: 121.4428,
    lat: 31.0268,
    name: "上海交通大学",
    value: 88,
    teams: 32,
    researchers: 290,
    papers: 3200,
    country: "中国",
  },
  {
    lng: 120.0848,
    lat: 30.2741,
    name: "浙江大学",
    value: 86,
    teams: 30,
    researchers: 280,
    papers: 3100,
    country: "中国",
  },
  {
    lng: 113.2644,
    lat: 23.1291,
    name: "中山大学",
    value: 84,
    teams: 28,
    researchers: 260,
    papers: 2900,
    country: "中国",
  },
  {
    lng: 116.3347,
    lat: 39.9359,
    name: "中国医学科学院",
    value: 82,
    teams: 25,
    researchers: 230,
    papers: 2600,
    country: "中国",
  },
  {
    lng: 118.7969,
    lat: 32.0603,
    name: "南京大学",
    value: 80,
    teams: 22,
    researchers: 210,
    papers: 2400,
    country: "中国",
  },
  {
    lng: 114.3896,
    lat: 30.5234,
    name: "武汉大学",
    value: 78,
    teams: 20,
    researchers: 190,
    papers: 2200,
    country: "中国",
  },
  {
    lng: 108.9435,
    lat: 34.2583,
    name: "西安交通大学",
    value: 76,
    teams: 18,
    researchers: 170,
    papers: 2000,
    country: "中国",
  },
  {
    lng: 126.6368,
    lat: 45.741,
    name: "哈尔滨工业大学",
    value: 74,
    teams: 16,
    researchers: 150,
    papers: 1800,
    country: "中国",
  },
  {
    lng: 104.0668,
    lat: 30.5728,
    name: "四川大学",
    value: 72,
    teams: 15,
    researchers: 140,
    papers: 1700,
    country: "中国",
  },
  {
    lng: 123.4315,
    lat: 41.8057,
    name: "东北大学",
    value: 70,
    teams: 14,
    researchers: 130,
    papers: 1600,
    country: "中国",
  },
  {
    lng: 117.2808,
    lat: 31.8669,
    name: "中国科学技术大学",
    value: 68,
    teams: 13,
    researchers: 120,
    papers: 1500,
    country: "中国",
  },
]

// 研究方向热度趋势数据
export const directionTrendData = [
  {
    year: "2018",
    空间转录组学: 3.5,
    RNA修饰与调控: 4.2,
    基因编辑治疗: 5.0,
    多组学整合分析: 4.8,
    肠道菌群与免疫: 3.8,
  },
  {
    year: "2019",
    空间转录组学: 4.2,
    RNA修饰与调控: 5.0,
    基因编辑治疗: 5.5,
    多组学整合分析: 5.2,
    肠道菌群与免疫: 4.5,
  },
  {
    year: "2020",
    空间转录组学: 5.5,
    RNA修饰与调控: 5.8,
    基因编辑治疗: 6.2,
    多组学整合分析: 5.8,
    肠道菌群与免疫: 5.2,
  },
  {
    year: "2021",
    空间转录组学: 6.8,
    RNA修饰与调控: 6.5,
    基因编辑治疗: 7.0,
    多组学整合分析: 6.5,
    肠道菌群与免疫: 6.0,
  },
  {
    year: "2022",
    空间转录组学: 8.0,
    RNA修饰与调控: 7.5,
    基因编辑治疗: 7.8,
    多组学整合分析: 7.2,
    肠道菌群与免疫: 7.0,
  },
  {
    year: "2023",
    空间转录组学: 9.0,
    RNA修饰与调控: 8.5,
    基因编辑治疗: 8.2,
    多组学整合分析: 8.0,
    肠道菌群与免疫: 7.8,
  },
]

// 研究方向领域分布数据
export const directionFieldData = [
  { type: "基础研究", value: 35 },
  { type: "应用研究", value: 28 },
  { type: "技术方法", value: 22 },
  { type: "临床转化", value: 15 },
]

// 期刊影响因子对比数据
export const journalImpactData = [
  { journal: "Nature", impactFactor: 69.504 },
  { journal: "Science", impactFactor: 63.714 },
  { journal: "Cell", impactFactor: 58.711 },
  { journal: "Nature Genetics", impactFactor: 49.962 },
  { journal: "Nature Biotechnology", impactFactor: 47.851 },
  { journal: "Nature Medicine", impactFactor: 44.714 },
  { journal: "Nature Methods", impactFactor: 39.217 },
  { journal: "Cell Stem Cell", impactFactor: 35.824 },
  { journal: "Genome Biology", impactFactor: 31.762 },
  { journal: "Nature Immunology", impactFactor: 30.985 },
]

// 期刊类型分布数据
export const journalTypeData = [
  { type: "综合性期刊", value: 25 },
  { type: "专业性期刊", value: 45 },
  { type: "开放获取期刊", value: 30 },
]

// 论文引用分布数据
export const paperCitationData = [
  { range: "0-10", count: 35 },
  { range: "11-50", count: 28 },
  { range: "51-100", count: 18 },
  { range: "101-500", count: 12 },
  { range: "500+", count: 7 },
]

// 学者排名数据
export const researcherRankingData = [
  {
    rank: 4,
    name: "陈静",
    avatar: "/placeholder.svg?key=jbvz4",
    institution: "清华大学",
    hIndex: 32,
    citations: 8500,
    papers: 78,
    trend: "up",
  },
  {
    rank: 5,
    name: "刘强",
    avatar: "/placeholder.svg?key=6lp24",
    institution: "上海交通大学",
    hIndex: 30,
    citations: 7800,
    papers: 72,
    trend: "up",
  },
  {
    rank: 6,
    name: "赵敏",
    avatar: "/placeholder.svg?key=bi99r",
    institution: "浙江大学",
    hIndex: 29,
    citations: 7200,
    papers: 68,
    trend: "stable",
  },
  {
    rank: 7,
    name: "孙宇",
    avatar: "/placeholder.svg?key=p9vc2",
    institution: "中国科学院",
    hIndex: 28,
    citations: 6900,
    papers: 65,
    trend: "up",
  },
  {
    rank: 8,
    name: "林华",
    avatar: "/placeholder.svg?key=m4xz7",
    institution: "复旦大学",
    hIndex: 27,
    citations: 6500,
    papers: 62,
    trend: "down",
  },
  {
    rank: 9,
    name: "郑重",
    avatar: "/placeholder.svg?key=k2qp5",
    institution: "北京大学",
    hIndex: 26,
    citations: 6200,
    papers: 60,
    trend: "up",
  },
  {
    rank: 10,
    name: "黄强",
    avatar: "/placeholder.svg?key=f7jn3",
    institution: "中山大学",
    hIndex: 25,
    citations: 5800,
    papers: 58,
    trend: "stable",
  },
]

// 团队排名数据
export const teamRankingData = [
  {
    rank: 4,
    name: "结构生物学与药物设计团队",
    institution: "清华大学",
    impact: 85,
    members: 16,
    papers: 145,
    citations: 12300,
    trend: "up",
  },
  {
    rank: 5,
    name: "合成生物学与基因编辑团队",
    institution: "上海交通大学",
    impact: 82,
    members: 20,
    papers: 168,
    citations: 13500,
    trend: "up",
  },
  {
    rank: 6,
    name: "病毒学与感染免疫研究团队",
    institution: "浙江大学",
    impact: 80,
    members: 19,
    papers: 182,
    citations: 15200,
    trend: "stable",
  },
  {
    rank: 7,
    name: "神经发育与疾病研究团队",
    institution: "中国科学院",
    impact: 78,
    members: 22,
    papers: 156,
    citations: 11800,
    trend: "up",
  },
  {
    rank: 8,
    name: "代谢组学研究团队",
    institution: "复旦大学",
    impact: 76,
    members: 15,
    papers: 142,
    citations: 10500,
    trend: "down",
  },
  {
    rank: 9,
    name: "表观遗传学研究团队",
    institution: "北京大学",
    impact: 74,
    members: 18,
    papers: 138,
    citations: 9800,
    trend: "up",
  },
  {
    rank: 10,
    name: "微生物组与健康研究团队",
    institution: "中山大学",
    impact: 72,
    members: 17,
    papers: 132,
    citations: 9200,
    trend: "stable",
  },
]

// 机构排名数据
export const institutionRankingData = [
  {
    rank: 1,
    name: "北京大学",
    type: "高校",
    score: 96,
    teams: 42,
    researchers: 380,
    papers: 4250,
    citations: 185000,
    trend: "up",
  },
  {
    rank: 2,
    name: "中国科学院",
    type: "科研院所",
    score: 94,
    teams: 56,
    researchers: 520,
    papers: 5100,
    citations: 210000,
    trend: "up",
  },
  {
    rank: 3,
    name: "清华大学",
    type: "高校",
    score: 92,
    teams: 38,
    researchers: 340,
    papers: 3800,
    citations: 165000,
    trend: "up",
  },
  {
    rank: 4,
    name: "复旦大学",
    type: "高校",
    score: 90,
    teams: 35,
    researchers: 310,
    papers: 3500,
    citations: 148000,
    trend: "up",
  },
  {
    rank: 5,
    name: "上海交通大学",
    type: "高校",
    score: 88,
    teams: 32,
    researchers: 290,
    papers: 3200,
    citations: 135000,
    trend: "up",
  },
  {
    rank: 6,
    name: "浙江大学",
    type: "高校",
    score: 86,
    teams: 30,
    researchers: 280,
    papers: 3100,
    citations: 128000,
    trend: "stable",
  },
  {
    rank: 7,
    name: "中山大学",
    type: "高校",
    score: 84,
    teams: 28,
    researchers: 260,
    papers: 2900,
    citations: 118000,
    trend: "up",
  },
  {
    rank: 8,
    name: "中国医学科学院",
    type: "科研院所",
    score: 82,
    teams: 25,
    researchers: 230,
    papers: 2600,
    citations: 105000,
    trend: "stable",
  },
  {
    rank: 9,
    name: "南京大学",
    type: "高校",
    score: 80,
    teams: 22,
    researchers: 210,
    papers: 2400,
    citations: 95000,
    trend: "up",
  },
  {
    rank: 10,
    name: "武汉大学",
    type: "高校",
    score: 78,
    teams: 20,
    researchers: 190,
    papers: 2200,
    citations: 88000,
    trend: "up",
  },
]

// 研究方向排名数据
export const directionRankingData = [
  {
    rank: 1,
    name: "空间转录组学",
    parent: "单细胞生物学",
    hotness: 9.0,
    growth: 45,
    papers: 450,
    researchers: 120,
    teams: 35,
    trend: "up",
  },
  {
    rank: 2,
    name: "RNA修饰与调控",
    parent: "RNA生物学",
    hotness: 8.5,
    growth: 32,
    papers: 380,
    researchers: 95,
    teams: 28,
    trend: "up",
  },
  {
    rank: 3,
    name: "基因编辑治疗",
    parent: "基因治疗",
    hotness: 8.2,
    growth: 38,
    papers: 410,
    researchers: 110,
    teams: 32,
    trend: "up",
  },
  {
    rank: 4,
    name: "多组学整合分析",
    parent: "生物信息学",
    hotness: 8.0,
    growth: 28,
    papers: 320,
    researchers: 85,
    teams: 25,
    trend: "up",
  },
  {
    rank: 5,
    name: "肠道菌群与免疫",
    parent: "微生物组学",
    hotness: 7.8,
    growth: 30,
    papers: 350,
    researchers: 90,
    teams: 26,
    trend: "up",
  },
  {
    rank: 6,
    name: "人工智能药物设计",
    parent: "药物研发",
    hotness: 7.5,
    growth: 42,
    papers: 280,
    researchers: 75,
    teams: 22,
    trend: "up",
  },
  {
    rank: 7,
    name: "外泌体与疾病标志物",
    parent: "分子诊断",
    hotness: 7.2,
    growth: 25,
    papers: 310,
    researchers: 80,
    teams: 24,
    trend: "stable",
  },
  {
    rank: 8,
    name: "蛋白质相互作用网络",
    parent: "蛋白质组学",
    hotness: 7.0,
    growth: 18,
    papers: 290,
    researchers: 75,
    teams: 22,
    trend: "stable",
  },
  {
    rank: 9,
    name: "脑器官样与神经发育",
    parent: "器官样",
    hotness: 6.8,
    growth: 35,
    papers: 240,
    researchers: 65,
    teams: 18,
    trend: "up",
  },
  {
    rank: 10,
    name: "免疫细胞工程",
    parent: "细胞治疗",
    hotness: 6.5,
    growth: 28,
    papers: 260,
    researchers: 70,
    teams: 20,
    trend: "up",
  },
]

// 论文排名数据
export const paperRankingData = [
  {
    rank: 1,
    title: "Single-cell RNA-seq reveals new types of human blood dendritic cells, monocytes, and progenitors",
    authors: "Villani AC, Satija R, Reynolds G, et al.",
    journal: "Science",
    year: 2017,
    citations: 3250,
    altmetric: 1820,
  },
  {
    rank: 2,
    title: "Comprehensive integration of single-cell data",
    authors: "Stuart T, Butler A, Hoffman P, et al.",
    journal: "Cell",
    year: 2019,
    citations: 2980,
    altmetric: 1650,
  },
  {
    rank: 3,
    title: "The human cell atlas: from vision to reality",
    authors: "Regev A, Teichmann SA, Lander ES, et al.",
    journal: "Nature",
    year: 2017,
    citations: 2750,
    altmetric: 1580,
  },
  {
    rank: 4,
    title: "CRISPR-Cas9 gene editing for human inherited diseases: molecular mechanisms and clinical applications",
    authors: "Li H, Yang Y, Hong W, et al.",
    journal: "Signal Transduction and Targeted Therapy",
    year: 2020,
    citations: 2480,
    altmetric: 1420,
  },
  {
    rank: 5,
    title: "Spatially resolved transcriptomics and beyond",
    authors: "Rao A, Barkley D, França GS, et al.",
    journal: "Nature Reviews Genetics",
    year: 2021,
    citations: 2150,
    altmetric: 1380,
  },
]

// 期刊排名数据
export const journalRankingData = [
  {
    rank: 1,
    name: "Nature",
    publisher: "Springer Nature",
    impactFactor: 69.504,
    fiveYearIF: 71.723,
    hIndex: 1159,
    citeScore: 75.6,
    trend: "up",
  },
  {
    rank: 2,
    name: "Science",
    publisher: "AAAS",
    impactFactor: 63.714,
    fiveYearIF: 65.382,
    hIndex: 1124,
    citeScore: 68.2,
    trend: "up",
  },
  {
    rank: 3,
    name: "Cell",
    publisher: "Elsevier",
    impactFactor: 58.711,
    fiveYearIF: 60.124,
    hIndex: 785,
    citeScore: 62.8,
    trend: "up",
  },
  {
    rank: 4,
    name: "Nature Genetics",
    publisher: "Springer Nature",
    impactFactor: 49.962,
    fiveYearIF: 52.847,
    hIndex: 624,
    citeScore: 54.3,
    trend: "up",
  },
  {
    rank: 5,
    name: "Nature Biotechnology",
    publisher: "Springer Nature",
    impactFactor: 47.851,
    fiveYearIF: 50.624,
    hIndex: 598,
    citeScore: 52.1,
    trend: "up",
  },
  {
    rank: 6,
    name: "Nature Medicine",
    publisher: "Springer Nature",
    impactFactor: 44.714,
    fiveYearIF: 46.982,
    hIndex: 582,
    citeScore: 48.7,
    trend: "up",
  },
  {
    rank: 7,
    name: "Nature Methods",
    publisher: "Springer Nature",
    impactFactor: 39.217,
    fiveYearIF: 41.568,
    hIndex: 456,
    citeScore: 43.2,
    trend: "up",
  },
  {
    rank: 8,
    name: "Cell Stem Cell",
    publisher: "Elsevier",
    impactFactor: 35.824,
    fiveYearIF: 37.215,
    hIndex: 321,
    citeScore: 38.5,
    trend: "stable",
  },
  {
    rank: 9,
    name: "Genome Biology",
    publisher: "BMC",
    impactFactor: 31.762,
    fiveYearIF: 33.124,
    hIndex: 298,
    citeScore: 34.8,
    trend: "up",
  },
  {
    rank: 10,
    name: "Nature Immunology",
    publisher: "Springer Nature",
    impactFactor: 30.985,
    fiveYearIF: 32.647,
    hIndex: 312,
    citeScore: 33.6,
    trend: "stable",
  },
]
